markdown: kramdown
pygments: true
baseurl: /blog
title: MyBlog
production_url: http://looooj.github.io
project_name: /blog

author :
  name : looooj
  email : ljgit@qq.com
  github : looooj

JB:
  version: 0.3.0
  BASE_PATH: /blog
  ASSET_PATH: false
  
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml
  
  comments :
    provider : disqus
    disqus :
      short_name : looooj
      
  sharing :
    provider : false
    
  analytics :
    provider : google 
    google : 
      tracking_id : 'UA-48005278-1'    
    
     